/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package whack_a_mole;

/**
 *
 * @author khatri
 */
public class homeScreen extends javax.swing.JFrame {

    /**
     * Creates new form homeScreen
     */
    public homeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jStartGame = new javax.swing.JMenuItem();
        jHistoryMenu = new javax.swing.JMenuItem();
        jExitMenu = new javax.swing.JMenuItem();
        menuAbt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Whack-a-Mole Game");
        setPreferredSize(new java.awt.Dimension(1370, 726));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Game");

        jStartGame.setMnemonic('s');
        jStartGame.setText("Start Game");
        jStartGame.setActionCommand("View History");
        jStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartGameActionPerformed(evt);
            }
        });
        fileMenu.add(jStartGame);

        jHistoryMenu.setMnemonic('o');
        jHistoryMenu.setText("View History");
        jHistoryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHistoryMenuActionPerformed(evt);
            }
        });
        fileMenu.add(jHistoryMenu);

        jExitMenu.setMnemonic('x');
        jExitMenu.setText("Exit");
        jExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(jExitMenu);

        menuBar.add(fileMenu);

        menuAbt.setText("About");
        menuAbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbtMouseClicked(evt);
            }
        });
        menuAbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbtActionPerformed(evt);
            }
        });
        menuBar.add(menuAbt);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitMenuActionPerformed

    private void jStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartGameActionPerformed
        // TODO add your handling code here:
       newGame ng=new newGame(new javax.swing.JFrame(),true);
       ng.setVisible(true);
    }//GEN-LAST:event_jStartGameActionPerformed

    private void jHistoryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHistoryMenuActionPerformed
        // TODO add your handling code here:
      gameHistory gh=new gameHistory(new javax.swing.JFrame(),true);
      gh.setVisible(true);
    }//GEN-LAST:event_jHistoryMenuActionPerformed

    private void menuAbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuAbtActionPerformed

    private void menuAbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbtMouseClicked
        // TODO add your handling code here:
        about ab=new about(new javax.swing.JFrame(),true);
        ab.setVisible(true);
    }//GEN-LAST:event_menuAbtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jExitMenu;
    private javax.swing.JMenuItem jHistoryMenu;
    private javax.swing.JMenuItem jStartGame;
    private javax.swing.JMenu menuAbt;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
